### ISSUE TITLE
Fan Control - Add control event entries in yaml for witherspoon

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#1792]
Once necessary sensors are available, add the following to the events yaml:
- [x] Add fan floor speed table based on ambient temp sensor(s) (openbmc/openbmc#940)
- [x] Add fan ceiling speed table based on ambient temp sensor(s) (openbmc/openbmc#1628)
- [x] Add fan control TctrlHigh/TctrlLow sensor(OCC) groups (openbmc/openbmc#1626)
- [x] Update all fan applications utilizing both rotor feedbacks

# **STATUS**
**7/25**
Vacation.
Using this issue to enable fan control functional areas as merged
Blockers - #1835 

**8/8**
Making updates in witherspoon yaml to support speed changes based on OCC temps

Verify results of making changes with current OCC state

Blockers - OCC driver binding & possibly #1839 

**8/9**
Updated witherspoon yaml with core temps, resulted in compiler issue
Generated code to large now with core sensors added so compiler gives warnings
Wrote up fan control status to thermal lead
Discussion with project mgmt on where fan control stands
Working to restructure generated code to generate source for each event

Determine generated code restructure
Update code generator python script to support restructure

Blockers - OCC interfacing(#2118)

**8/10**
Performing end-to-end integration testing
Debugged that the OCC core temps are invalid being provided from OCC, Todd working with OCC team
Completed a fix on group property values not existing for set speed event actions
Updated set speed events with interfacesAdded signals
Working on an update to allow a factor to be applied on inc/dec speed actions

Finish inc/dec action factor update
Resume end-to-end fan control testing

Blockers - OCC interfacing(#2118), OCC invalid temp values

**8/11**
Adjusted speed increase single delta factor and verified this works with OCC milliC temps correctly
Debug speed decrease oscillations, cause is fans marked as non-functional
Able to get a speed decrease, but then held an new requested speed since temps remain unchanged
Determine speed decrease timer interval change to request additional decreases to floor

Update for recurring speed decrease requests

Blockers - OCC interfacing(#2118)

**8/14**
Discussed MSL enforcement options with Salim, implement in mfg tools
Pushed update to inc/dec actions containing a factor param
Design idea to attach optional timer to speed event actions
Discussed and informed thermal team member on how to manually set fan speeds using REST
Completed implementing speed event timer

Clean-up speed event timer implementation
Add option speed event timer to yaml and parser

Blockers - OCC interfacing(#2118)

**8/15**
Pushed up speed event timer support
Fixed zone's active control state
Basic auto fan control testing successfully
Updating staged integration of sensors used for controlling fan speeds

Blockers - OCC interfacing(#2118)

**Comment by msbarth** [comment]
Speed increase and decrease base example for fan-control events.yaml update:

groups:
    - name: zone0_cores
      description: Group of core temperature sensors for zone 0
      type: sensors
      members:
          - /temperature/p0_core0_temp
          - /temperature/p0_core1_temp
          - /temperature/p0_core2_temp
          - /temperature/p0_core3_temp
          - /temperature/p0_core4_temp
          - /temperature/p0_core5_temp
          - /temperature/p0_core6_temp
          - /temperature/p0_core7_temp
          - /temperature/p0_core8_temp
          - /temperature/p0_core9_temp
          - /temperature/p0_core10_temp
          - /temperature/p0_core11_temp
          - /temperature/p0_core12_temp
          - /temperature/p0_core13_temp
          - /temperature/p0_core14_temp
          - /temperature/p0_core15_temp
          - /temperature/p0_core16_temp
          - /temperature/p0_core17_temp
          - /temperature/p0_core18_temp
          - /temperature/p0_core19_temp
          - /temperature/p0_core20_temp
          - /temperature/p0_core21_temp
          - /temperature/p0_core22_temp
          - /temperature/p0_core23_temp
          - /temperature/p1_core0_temp
          - /temperature/p1_core1_temp
          - /temperature/p1_core2_temp
          - /temperature/p1_core3_temp
          - /temperature/p1_core4_temp
          - /temperature/p1_core5_temp
          - /temperature/p1_core6_temp
          - /temperature/p1_core7_temp
          - /temperature/p1_core8_temp
          - /temperature/p1_core9_temp
          - /temperature/p1_core10_temp
          - /temperature/p1_core11_temp
          - /temperature/p1_core12_temp
          - /temperature/p1_core13_temp
          - /temperature/p1_core14_temp
          - /temperature/p1_core15_temp
          - /temperature/p1_core16_temp
          - /temperature/p1_core17_temp
          - /temperature/p1_core18_temp
          - /temperature/p1_core19_temp
          - /temperature/p1_core20_temp
          - /temperature/p1_core21_temp
          - /temperature/p1_core22_temp
          - /temperature/p1_core23_temp
actions:
    - name: set_net_increase_speed
      description: Set the speed increase delta based on sensor's value and increase size
      parameters:
          - property
          - delta
    - name: set_net_decrease_speed
      description: Set the speed decrease deleta base on sensor's value and decrease size
      parameters:
          - property
          - delta
events:
    - name: speed_increase_changes_based_on_core_temps
      zone_conditions:
          - name: air_cooled_chassis
            zones:
                - 0
          - name: water_and_air_cooled_chassis
            zones:
                - 0
      group: zone0_cores
      interface: xyz.openbmc_project.Control.FanSpeed
      property:
          name: Target
          type: uint64_t
      action:
          name: set_net_increase_speed
          property: 73000
          delta:
              value: 400
              type: uint64_t
    - name: speed_decrease_changes_based_on_core_temps
      zone_conditions:
          - name: air_cooled_chassis
            zones:
                - 0
          - name: water_and_air_cooled_chassis
            zones:
                - 0
      group: zone0_cores
      interface: xyz.openbmc_project.Control.FanSpeed
      property:
          name: Target
          type: uint64_t
      action:
          name: set_net_decrease_speed
          property: 70000
          delta:
              value: 40
              type: uint64_t

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6032> Add fan speed inc/dec control based on core temps
Resolves  #1792 Fan Control - Add control event entries in yaml for witherspoon
