### ISSUE TITLE
Milestone: XCAT 3

### ISSUE THREAD

**Issue by bradbishop** [openbmc/openbmc#1880]
End of July.

**Comment by sivassrr** [comment]
@bradbishop What are all changes can we expect here.  Let know if there is any recommended Test Cases as well. That helps and thank you @bradbishop

**Comment by sivassrr** [comment]
Are we going to consider rvitals as well.

**Comment by whowutwut** [comment]
@sivassrr  xCAT team has implemented support for `rvitals` as a generic pass through, so anything new added to the REST response should be displayed by the xCAT `rvitals ` command.   I think that can be pushed to lower priority. Is there something specific you were asking about when you say `rvitals`?

**Comment by whowutwut** [comment]
For this milestone, I'd like to push the following minimum set of functions to be delivered to the top: 

- [ ] VLAN Tagging support inband
- [ ] Ability to flash firmware (OpenBMC & PNOR) using REST commands

If time persists:  
- [ ] Exposing the [Network](https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/Network) API into the build
