### ISSUE TITLE
Modify commit-tracker in openbmc-build-scripts to identify the tags for an issue/repo.

### ISSUE THREAD

**Issue by lgon** [openbmc/openbmc#2331]
Modify the the commit-tracker script in openbmc-build-scripts to take a github issue, and a GHE or github repo and track down which tag(s) that issue (if any) has gone into.

Tasklist

- [ ] Add issue number paramter to the commit-tracker script.
- [ ] Add tag parameter to the commit-tracker script.
- [ ] Have commit-tracker search the repo given in the parameter for tags used by the given issue.
