### ISSUE TITLE
Milestone: Core - Advanced Code Update

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#349]

**Comment by anoo1** [comment]
PNOR Story list:
- [ ] Add UBI support in the kernel.
- [ ] Add UBIFS support in the kernel.
- [ ] Create tool for PNOR-to-OpenBMC format (CRAMFS).
- [ ] Create program for creating/updating UBI volumes.
- [ ] Create new mailboxd replacement.
- [ ] Create dbus objects for software.Version.

BMC Story list:
- [ ] Make current rootfs footprint smaller (Remove gdbus, include .pyc instead of .py, remove perl, upgrade systemd).
- [ ] Define needed filesystems. First identify what the current partitions serve for.
