### ISSUE TITLE
Witherspoon Power-On

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#646]

**Comment by geissonator** [comment]
### external requirements

- [ ] A build/release of openbmc from Cliff S. and team to release to the lab
- [ ] OpenFSI support from Chris Bostic, including the ability to run "putcfam pu 2801 80000000"
- [ ] Required Witherspoon MRW from Sertac out in op-build
