### ISSUE TITLE
getvpd: Generate required data for VPD from MRW

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#681]
FRU, IPMI, and OpenPower VPD inventory objects will require information from the MRW.  This issue tracks getting that data into the MRW and then into a format that these objects can consume.

**Comment by geissonator** [comment]
@dkodihal and @ratagupt could you please summarize what you need with this story?

**Comment by ratagupt** [comment]
- [ ] Listing of the data which is required  from MRW for HOST VPD.

- [ ] Listing of the data which is required from MRW for openPowerVPD.

- [ ] Listing of the data which is required  from MRW for EEPROM VPD. 

- [ ] Prepare a format of YAML file which is having all the three data. 

- [ ] Parse the data from MRW and generate YAML file including data for HOST VPD.

- [ ] Parse the data from MRW for EEPROM VPD and add it into the YAML file.

- [ ] Parse the data from MRW for openpower VPD and add it into the YAML file.
