### ISSUE TITLE
Merge dbus interface and error log meta data definition

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#731]

**Comment by geissonator** [comment]
Task List
- [ ] Define yaml format in dbus repo for error codes, upload code showing example
- [ ] Update recipes to handle dependency between dbus yaml and logging yaml (ensure we build dbus first and export it's yaml for logging repo to use)
- [ ] Define meta data for dbus defined error within logging repo, compile script should merge the 2 into the generated hpp file

Questions: The dbusplus code will probably require the generated hpp file from the log component (error validation and exception handling), can our build env handle this dual dependency issue?

**Comment by geissonator** [comment]
The final part of this requires some more work within the phosphor-dbus-interfaces repo (i.e. the initial makefile and recipes need to be created).   Then the work from this story can be run as a part of that build process.  Going to reduce this to 2 pts for the work to the scripts and create a seperate 1 pointer to incorporate them into the phopshor-dbus-interface repo once that work is done.
